apiVersion: v1
kind: Secret
metadata:
  name: example-204-validating-certs
type: Opaque
data:
  server.crt: |
    {{ .Files.Get "validating-certs/server.crt" | b64enc }}
  server-key.pem: |
    {{ .Files.Get "validating-certs/server-key.pem" | b64enc }}
  cluster-ca.pem: |
    {{ .Files.Get "validating-certs/cluster-ca.pem" | b64enc }}
#  client-ca.pem: |
    {{/*  .Files.Get "validating-certs/client-ca.pem" | b64enc */}}
