---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shell-operator-validating-acc

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: shell-operator-validating
rules:
#- apiGroups: [""]
#  resources: ["namespaces"]
#  verbs: ["get", "watch", "list"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: shell-operator-validating
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shell-operator-validating
subjects:
  - kind: ServiceAccount
    name: shell-operator-validating-acc
    namespace: {{ .Release.Namespace }}
